version: '3.7'
services:
  wireguard-sp:
    image: linuxserver/wireguard:latest
    container_name: wireguard-client-saopaulo
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris #set correct timezone
      - LOG_CONFS=true
      - AUTOCONNECT=true
    ports:
      - 51820:51820/udp
    volumes:
      - /home/opc/code/crazybot/vpn/config/br-sao-wg-201.conf:/config/wg0.conf
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: always
  wireguard-uk:
    image: linuxserver/wireguard:latest
    container_name: wireguard-client-london
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris #set correct timezone
      - LOG_CONFS=true
      - AUTOCONNECT=true
    ports:
      - 51830:51830/udp
    volumes:
      - /home/opc/code/crazybot/vpn/config/gb31-wireguard.conf:/config/wg0.conf
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: always
